#Read10X(".")
Data <- Read10X(".")
Data = scQC(Data, mtThreshold = 0.05)
#CreateSeuratObject(Data)
Data = CreateSeuratObject(Data)
#NormalizeData(Data)
Data = NormalizeData(Data)
#
Data = FindVariableFeatures(Data)
Data = ScaleData(Data)
Data = RunPCA(Data)
Data = RunTSNE(Data)
TSNEPlot(Data)
FeaturePlot(Data, c("Ikzf2","Cd4","Il2ra","Entpd1","Foxp3","Folr1", "Lrrc32", "Itgb8", "Il1r1" ,"Il10"), order= TRUE)
FeaturePlot(Data, c("Maf", "Tnfrsf18", "Cngb1", "Izumo1r", "Lag3", "Ccr4", "Ctla4", "Tnfrsf4", "Itgae"), order= TRUE)
FeaturePlot(Data, c("Nt5e", "Sell", "Cd27", "Cd28","Il7r","Pdcd1","Il2rb","Il2rg","Klrg1", "Cd38", "Cd69"), order= TRUE)                   
FeaturePlot(Data, c("Itgal","Ccr4","Ccr5","Ccr6","Ccr9","Ccr10", "Cxcr3", "Cxcr4", "Gzma", "Gzmb", "Prf1"), order= TRUE)                   
VG = VariableFeatures(Data)
FeaturePlot(Data, VG[1:10], order = TRUE)
